"""Companies table

Revision ID: 03d54c3d4749
Revises: fb6c89f3fd54
Create Date: 2019-08-24 16:10:58.864602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d54c3d4749'
down_revision = 'fb6c89f3fd54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_symbol', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_companies_company_symbol'), 'companies', ['company_symbol'], unique=True)
    op.drop_index('ix_companies_company_name', table_name='companies')
    op.create_index(op.f('ix_companies_company_name'), 'companies', ['company_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_company_name'), table_name='companies')
    op.create_index('ix_companies_company_name', 'companies', ['company_name'], unique=1)
    op.drop_index(op.f('ix_companies_company_symbol'), table_name='companies')
    op.drop_column('companies', 'company_symbol')
    # ### end Alembic commands ###
