"""Company table

Revision ID: 292daf9bb8c6
Revises: 03d54c3d4749
Create Date: 2019-08-24 17:01:10.097432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292daf9bb8c6'
down_revision = '03d54c3d4749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_symbol', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_company_name'), 'company', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_company_symbol'), 'company', ['company_symbol'], unique=True)
    op.drop_index('ix_companies_company_name', table_name='companies')
    op.drop_index('ix_companies_company_symbol', table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('company_symbol', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_companies_company_symbol', 'companies', ['company_symbol'], unique=1)
    op.create_index('ix_companies_company_name', 'companies', ['company_name'], unique=False)
    op.drop_index(op.f('ix_company_company_symbol'), table_name='company')
    op.drop_index(op.f('ix_company_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
