"""new fields in user model

Revision ID: 929eaf084b14
Revises: 9d6f560e541e
Create Date: 2019-04-20 15:48:57.776580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929eaf084b14'
down_revision = '9d6f560e541e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
